### ISSUE TITLE
No installation guide

### ISSUE THREAD

**Issue by agozie** [themattman/mongodb-raspberrypi-docker#2]
I could not find how to install this on a raspberry pi.

**Comment by themattman** [comment]
At the moment, this repo is intended for users who are a little more proactive with debugging and have a background with Docker (since I do not). I'm still ironing out how to build and distribute the docker images correctly. This repo doesn't command as much of my attention as does the [binaries](https://github.com/themattman/mongodb-raspberrypi-binaries) themselves because that is the foundation of running MongoDB on a Raspberry Pi. I'm able to run the docker images in this repo on the same Pi that I built them with, but I understand that isn't a guarantee they will work for others and there may be important steps needed to properly distribute the images. In other words - this repo is a work in progress. Please feel free to make suggestions if you are able to use the images yourself.

**Comment by boomam** [comment]
I created a PR with some **very** basic steps here -  
https://github.com/themattman/mongodb-raspberrypi-docker/pull/3  
If it gets merged, great, if not, dive into the PR and grab the steps from the updated readme.

**Comment by themattman** [comment]
Looking closer, the steps provided by @boomam are for users that want to recreate the docker images themselves. While you are free to do that, my goal was to provide the images directly to users.

I have [added steps to the main README](https://github.com/themattman/mongodb-raspberrypi-docker#how-to-install) that detail how to load the images directly onto your machine.
